#!/bin/bash
# ------------------------------------------------------
#	labs-get v1.0.0-lx
#	Date Created: 12/25/2015
#	Date Edited: 12/26/2015
#	Copyright (C) 2015 Digital Warrior Labs
#	Author: Nathan Martindale (WildfireXIII)
# ------------------------------------------------------

declare -a g_workingArray
declare -a g_workingArray2
declare -a g_listDataArray
declare -a g_installedDataArray
declare -a g_dependenciesArray
declare -a g_tagsArray
declare -a g_filterArray

g_workingData=""
g_workingBool=false

# --------------------------- FUNCTIONS ------------------------------

# ASSIGNS: g_workingArray
function readListFile()
{
	unset g_workingArray
	i=0
	while read line; do
		if [[ $i -ne 0 ]]; then # dont' get the first line
			g_workingArray[$i]=$line
		fi
		((i++))
	done < $LIST_DATA_FILE
}

# ASSIGNS: g_workingArray
function readInstalledFile()
{
	unset g_workingArray
	i=0
	while read line; do
		if [[ $i -ne 0 ]]; then # don't get first line
			g_workingArray[$i]=$line 
		fi
		((i++))
	done < $INSTALLED_DATA_FILE
}

# ASSIGNS: g_workingData
function getCSVCol() # pass in $1 as rowData, and $2 as colNum
{
	unset g_workingData
	IFS=',' read -ra Cols <<< "$1"
	g_workingData="${Cols[$2]}"
}

# ASSIGNS: g_workingArray
function getTagList() # $1 should be tag string
{
	unset g_workingArray
	IFS='|' read -ra Tags <<< "$1"
	g_workingArray=("${Tags[@]}")
}

# ASSIGNS: g_workingArray2
# REQUIRES: g_listDataArray or g_installedDataArray, g_filterArray
function filterPackageListByTags() # pass in $1 as true if installed, false if not
{
	#echo "uh, HELLO" # DEBUG
	newIndex=0
	unset g_workingArray2
	#echo "1:$1" # DEBUG
	if [[ "$1" = true ]]; then
		#echo "I'm a bug, and inside here even though I shouldnt' be.." # DEBUG
		for i in "${g_installedDataArray[@]}"
		do
			# fill tag array first
			unset g_workingArray
			getCSVCol "$i" 3 # assigns to g_workingData
			getTagList "$g_workingData" # assigns to g_workingArray
			g_tagsArray=("${g_workingArray[@]}")

			# check if should filter
			shouldFilter # assigns to g_workingBool
			if [[ "$g_workingBool" = false ]]; then
				g_workingArray2[$newIndex]="$i"
				((newIndex++))
			fi
		done
	else
		#echo "YO DAWG" # DEBUG
		for i in "${g_listDataArray[@]}"
		do
			#echo "line:$i" # DEBUG
			# fill tag array first
			unset g_workingArray
			getCSVCol "$i" 4 # assigns to g_workingData
			#echo "tags:$g_workingData" # DEBUG
			getTagList "$g_workingData" # assigns to g_workingArray
			g_tagsArray=("${g_workingArray[@]}")

			# check if should filter
			shouldFilter # assigns to g_workingBool
			if [[ "$g_workingBool" = false ]]; then
				g_workingArray2[$newIndex]="$i"
				#echo "is now: ${g_workingArray2[$newIndex]}" # DEBUG
				((newIndex++))
			fi
		done
	fi
}

# ASSIGNS: g_workingBool
# REQUIRES: g_tagsArray, g_filterArray
# sets g_workingBool to false if it should NOT filter, true if it should
function shouldFilter()
{
	tagFound=false
	notTagFound=false # if negativefilter is in affect

	# if no filter tags found, we're good
	if [[ "${g_filterArray[0]}" == "" ]]; then
		g_workingBool=false
		return
	fi
	
	for filter in "${g_filterArray[@]}"
	do
		# check for first letter is '!'
		negativeFilter=false
		if [[ ${filter:0:1} == "!" ]]; then
			negativeFilter=true
			filter="${filter:1}"
		fi

		# reset booleans
		tagFound=false
		notTagFound=false

		for tag in "${g_tagsArray[@]}"
		do
			#echo "checking $filter with $tag" # DEBUG
			if [[ "$filter" == "$tag" ]];	then
				#echo "Found match!" # DEBUG
				tagFound=true	
				if [[ "$negativeFilter" = true ]]; then
					#echo "(but wasn't supposed to match)" # DEBUG
					notTagFound=true
				fi
			fi
			if [[ "$notTagFound" = true ]]; then
				g_workingBool=true
				return
			fi
		done
		if [[ "$notTagFound" = true ]]; then
			g_workingBool=true
			return
		fi

		if [[ "$tagFound" = false ]]; then
			g_workingBool=true
			return
		fi
	done

	# we've made it this far and haven't been disqualified so this one shouldn't be filtered!
	g_workingBool=false
}



# --------------------------- MAIN PROGRAM FLOW ------------------------------
# get command line arguments

list=false
check=false
update=""


if [[ $1 == "-list" ]]; then
	echo "thing"
fi

if [[ $1 == "-install" ]]; then 
	echo "thing"
fi

if [[ $1 == "-update" ]]; then
	echo "thing"
fi

if [[ $1 == "-remove" ]]; then
	echo "thing"
fi

# other info is going to be 2nd argument only, then we have to do the same checks

# check that the necessary environemnt variables


# shortcuts to important files
LIST_DATA_FILE="$PKG_DIR/labs-get-list/list.dat"
INSTALLED_DATA_FILE="$DATA_DIR/labs-get/installed.dat"
DEFAULT_TAGS_FILE="$DATA_DIR/labs-get/default-tags.dat"
flag_importantFilesNotFound=false

# check for important file existence
if [ ! -e $LIST_DATA_FILE ]; then
	echo "ERROR - Couldn't find $LIST_DATA_FILE" #TODO: ADD COLOR	
	$flag_importantFilesNotFound = true
fi
if [ ! -e $INSTALLED_DATA_FILE ]; then
	echo "ERROR - Couldn't find $INSTALLED_DATA_FILE" #TODO: ADD COLOR	
	$flag_importantFilesNotFound = true
fi
if [ ! -e $DEFAULT_TAGS_FILE ]; then
	echo "ERROR - Couldn't find $DEFAULT_TAGS_FILE" #TODO: ADD COLOR	
	$flag_importantFilesNotFound = true
fi

if $flag_importantFilesNotFound; then
	echo "Necessary data files could not be found. Please re-run the setup script that came with the package."
	exit
fi

readListFile
g_listDataArray=("${g_workingArray[@]}")

g_filterArray[0]="linux"

filterPackageListByTags false
g_listDataArray=("${g_workingArray2[@]}")


for i in "${g_listDataArray[@]}"
do
	echo "Yay! $i"
done


